Repository AY2425S1-CS2103T-W12-2/tp, pull requests merged in 2024-10, with the labels that each got.

#52 Add feature to export volunteers as CSV file
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High

#79 Add feature to assign volunteers
  data/addressbook.json
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/VolunteerParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/volunteer/Volunteer.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedVolunteer.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/VolunteerCard.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/VolunteerListCard.fxml
Labels: priority.High

#74 Add EventDeleteCommand, VolunteerDeleteCommand and corresponding Parsers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/eventcommands/EventDeleteCommand.java
  src/main/java/seedu/address/logic/commands/eventcommands/EventNewCommand.java
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerDeleteCommand.java
  src/main/java/seedu/address/logic/parser/VolunteerParserUtil.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventNewCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/VolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/VolunteerDeleteCommandParser.java
Labels: priority.High

#75 Add display reset command.
  src/main/java/seedu/address/logic/commands/ResetDisplayListsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High

#85 View event/volunteer commands and parsers
  src/main/java/seedu/address/logic/commands/eventcommands/EventViewCommand.java
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerViewCommand.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventViewCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/VolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/VolunteerViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventParticipatedByVolunteerPredicate.java
  src/main/java/seedu/address/model/volunteer/Volunteer.java
  src/main/java/seedu/address/model/volunteer/VolunteerInvolvedInEventPredicate.java
Labels: priority.Medium

#83 Find event and volunteer function
  src/main/java/seedu/address/logic/commands/eventcommands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/volunteercommands/FindVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerAddCommand.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/FindEventCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/FindVolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/VolunteerAddCommandParser.java
  src/main/java/seedu/address/logic/parser/volunteercommandparser/VolunteerCommandParser.java
Labels: priority.High

#81 Use index for assign command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/VolunteerCard.java
Labels: priority.High

#78 Launch help using javafx browser
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/HostServiceManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium

#77 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: priority.Medium

#87 Adjustments to v1.3
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/volunteer/UniqueVolunteerList.java
  src/main/java/seedu/address/model/volunteer/Volunteer.java
Labels: priority.High

#95 Remove person class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/EventParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/volunteer/Email.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#100 Enforce events to start before it ends
  src/main/java/seedu/address/logic/parser/eventcommandparser/EventNewCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/event/exceptions/ChronologicalOrderException.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
Labels: priority.High

#103 Changed AB3 icon to a placeholder icon
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/VolunSync_Icon_Placeholder.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.Low

#105 Export participants and involvedIn
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventParticipatedByVolunteerPredicate.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/volunteer/Volunteer.java
Labels: priority.High

#110 Refactor AddressBook
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/EventManager.java
  src/main/java/seedu/address/model/VolunteerManager.java
Labels: priority.Medium

#115 Update User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EventParserUtil.java
Labels: priority.High

#117 Test event model
  src/main/java/seedu/address/logic/commands/eventcommands/EventNewCommand.java
  src/main/java/seedu/address/model/event/Date.java
  src/main/java/seedu/address/model/event/Description.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventName.java
  src/main/java/seedu/address/model/event/Location.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/event/DateTest.java
  src/test/java/seedu/address/model/event/DescriptionTest.java
  src/test/java/seedu/address/model/event/EventNameTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/LocationTest.java
  src/test/java/seedu/address/model/event/TimeTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High

#116 Add exception to handle volunteer assignment to overlapping events
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/EventManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Date.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/exceptions/OverlappingAssignException.java
Labels: priority.High

#112 Update parser util and addressbook parser tests
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/logic/commands/eventcommands/EventNewCommand.java
  src/main/java/seedu/address/logic/commands/volunteercommands/VolunteerNewCommand.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EventParserUtilTest.java
  src/test/java/seedu/address/logic/parser/VolunteerParserUtilTest.java
Labels: priority.High

#122 Update UiClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High
